name: scalapay_integration
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  http:
  cupertino_icons: ^0.1.3
  splashscreen:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

